/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import java.awt.*;

/**
 *
 * @author Chenul Warnasooriya
 */
public class customerPotral extends javax.swing.JFrame {

    private String customerName = "Guest Customer"; // Default customer name

    /**
     * Creates new form customerPotral
     */
    public customerPotral() {
        initComponents();
        setupTable();
        loadMarketplaceProducts();
        addPreOrderListener();
    }

    /**
     * Constructor with customer name
     */
    public customerPotral(String customerName) {
        this.customerName = customerName;
        initComponents();
        setupTable();
        loadMarketplaceProducts();
        addPreOrderListener();
    }

    // Add action listener to Pre-Order button
    private void addPreOrderListener() {
        jButton4.addActionListener(e -> showPreOrderDialog());
    }

    // Setup table columns
    private void setupTable() {
        String[] columns = {"ID", "Product", "Farmer", "Price", "Available", "Category", "Status"};
        DefaultTableModel model = new DefaultTableModel(columns, 0);
        jTable1.setModel(model);
    }

    // Load marketplace products from database
    private void loadMarketplaceProducts() {
        // Create table if not exists
        MarketplaceDAO.createMarketplaceTable();
        CustomerOrderDAO.createOrdersTable();

        // Get all approved products
        List<Object[]> products = MarketplaceDAO.getAllProducts();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        for (Object[] product : products) {
            // Only show approved products
            if ("Approved".equals(product[6])) {
                // Get category from database
                int productId = (int) product[0];
                Object[] fullProduct = MarketplaceDAO.getProductById(productId);
                String category = fullProduct != null ? (String) fullProduct[6] : "N/A";

                Object[] row = {
                    product[0],  // ID
                    product[1],  // Product Name
                    product[2],  // Farmer Name
                    product[3],  // Price
                    product[4],  // Available Quantity
                    category,    // Category
                    product[5]   // Status
                };
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Dashboard");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buy Anything You Want");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(273, 273, 273))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setBorder(new javax.swing.border.MatteBorder(null));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/store.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");

        jButton1.setBackground(new java.awt.Color(0, 204, 0));
        jButton1.setText("Buy Product");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setText("Refresh for Products");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plant.jpg"))); // NOI18N
        jLabel4.setText("jLabel2");

        jButton4.setBackground(new java.awt.Color(255, 255, 0));
        jButton4.setText("Pre-Order Products");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Buy Product functionality
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a product to buy!", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Get product details from selected row
        int productId = (int) jTable1.getValueAt(selectedRow, 0);
        String productName = (String) jTable1.getValueAt(selectedRow, 1);
        String farmerName = (String) jTable1.getValueAt(selectedRow, 2);
        String priceStr = (String) jTable1.getValueAt(selectedRow, 3);
        String availableStr = (String) jTable1.getValueAt(selectedRow, 4);

        // Get full product details
        Object[] product = MarketplaceDAO.getProductById(productId);
        if (product == null) {
            JOptionPane.showMessageDialog(this, "Product not found!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        double price = (double) product[3];
        int availableQty = (int) product[4];
        String unit = (String) product[5];

        // Ask for quantity
        String quantityStr = JOptionPane.showInputDialog(this,
            "Enter quantity to purchase (Available: " + availableQty + " " + unit + "):",
            "Purchase Quantity",
            JOptionPane.QUESTION_MESSAGE);

        if (quantityStr == null || quantityStr.trim().isEmpty()) {
            return; // User cancelled
        }

        try {
            int quantity = Integer.parseInt(quantityStr);

            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0!", "Invalid Quantity", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (quantity > availableQty) {
                JOptionPane.showMessageDialog(this, "Not enough stock! Available: " + availableQty + " " + unit, "Insufficient Stock", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Calculate total
            double totalAmount = price * quantity;

            // Confirm purchase
            int confirm = JOptionPane.showConfirmDialog(this,
                "Product: " + productName + "\n" +
                "Farmer: " + farmerName + "\n" +
                "Quantity: " + quantity + " " + unit + "\n" +
                "Price: $" + price + "/" + unit + "\n" +
                "Total: $" + totalAmount + "\n\n" +
                "Confirm purchase?",
                "Confirm Purchase",
                JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Add order to database
                boolean success = CustomerOrderDAO.addOrder(
                    customerName,
                    productId,
                    productName,
                    farmerName,
                    quantity,
                    unit,
                    price,
                    totalAmount
                );

                if (success) {
                    JOptionPane.showMessageDialog(this,
                        "Order placed successfully!\n" +
                        "Total Amount: $" + totalAmount + "\n" +
                        "Order Status: Pending",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);

                    // Refresh the product list
                    loadMarketplaceProducts();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to place order!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number!", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Refresh products
        loadMarketplaceProducts();
        JOptionPane.showMessageDialog(this, "Product list refreshed!\nShowing latest products from marketplace.", "Refreshed", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Show pre-order dialog
    private void showPreOrderDialog() {
        JDialog dialog = new JDialog(this, "Pre-Order Products", true);
        dialog.setLayout(new GridBagLayout());
        dialog.setSize(500, 500);
        dialog.setLocationRelativeTo(this);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 15, 10, 15);

        // Title
        JLabel titleLabel = new JLabel("🛒 Pre-Order Product");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
        titleLabel.setForeground(new Color(255, 0, 153));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        dialog.add(titleLabel, gbc);

        gbc.gridwidth = 1;

        // Product Name
        gbc.gridy = 1;
        gbc.gridx = 0;
        JLabel productLabel = new JLabel("Product Name:");
        productLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(productLabel, gbc);

        gbc.gridx = 1;
        JTextField productField = new JTextField(20);
        dialog.add(productField, gbc);

        // Quantity
        gbc.gridy = 2;
        gbc.gridx = 0;
        JLabel quantityLabel = new JLabel("Quantity:");
        quantityLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(quantityLabel, gbc);

        gbc.gridx = 1;
        JTextField quantityField = new JTextField(20);
        dialog.add(quantityField, gbc);

        // Unit
        gbc.gridy = 3;
        gbc.gridx = 0;
        JLabel unitLabel = new JLabel("Unit:");
        unitLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(unitLabel, gbc);

        gbc.gridx = 1;
        String[] units = {"kg", "lbs", "pieces", "bags", "boxes"};
        JComboBox<String> unitCombo = new JComboBox<>(units);
        dialog.add(unitCombo, gbc);

        // Expected Delivery Date
        gbc.gridy = 4;
        gbc.gridx = 0;
        JLabel deliveryDateLabel = new JLabel("Expected Delivery (YYYY-MM-DD):");
        deliveryDateLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(deliveryDateLabel, gbc);

        gbc.gridx = 1;
        JTextField deliveryDateField = new JTextField("2025-01-01");
        dialog.add(deliveryDateField, gbc);

        // Contact Number
        gbc.gridy = 5;
        gbc.gridx = 0;
        JLabel contactLabel = new JLabel("Contact Number:");
        contactLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(contactLabel, gbc);

        gbc.gridx = 1;
        JTextField contactField = new JTextField(20);
        dialog.add(contactField, gbc);

        // Delivery Address
        gbc.gridy = 6;
        gbc.gridx = 0;
        JLabel addressLabel = new JLabel("Delivery Address:");
        addressLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(addressLabel, gbc);

        gbc.gridx = 1;
        JTextArea addressArea = new JTextArea(3, 20);
        addressArea.setLineWrap(true);
        JScrollPane addressScroll = new JScrollPane(addressArea);
        dialog.add(addressScroll, gbc);

        // Notes
        gbc.gridy = 7;
        gbc.gridx = 0;
        JLabel notesLabel = new JLabel("Additional Notes:");
        notesLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(notesLabel, gbc);

        gbc.gridx = 1;
        JTextArea notesArea = new JTextArea(2, 20);
        notesArea.setLineWrap(true);
        JScrollPane notesScroll = new JScrollPane(notesArea);
        dialog.add(notesScroll, gbc);

        // Buttons
        gbc.gridy = 8;
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));

        JButton submitButton = new JButton("✓ Submit Pre-Order");
        submitButton.setBackground(new Color(255, 0, 153));
        submitButton.setForeground(Color.WHITE);
        submitButton.setFont(new Font("Arial", Font.BOLD, 13));
        submitButton.setFocusPainted(false);
        submitButton.setOpaque(true);
        submitButton.setBorderPainted(false);
        submitButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        JButton cancelButton = new JButton("❌ Cancel");
        cancelButton.setBackground(new Color(220, 53, 69));
        cancelButton.setForeground(Color.WHITE);
        cancelButton.setFont(new Font("Arial", Font.BOLD, 13));
        cancelButton.setFocusPainted(false);
        cancelButton.setOpaque(true);
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new Cursor(Cursor.HAND_CURSOR));

        btnPanel.add(submitButton);
        btnPanel.add(cancelButton);
        dialog.add(btnPanel, gbc);

        // Submit button action
        submitButton.addActionListener(e -> {
            String productName = productField.getText().trim();
            String quantityStr = quantityField.getText().trim();
            String unit = (String) unitCombo.getSelectedItem();
            String deliveryDate = deliveryDateField.getText().trim();
            String contactNumber = contactField.getText().trim();
            String address = addressArea.getText().trim();
            String notes = notesArea.getText().trim();

            if (productName.isEmpty() || quantityStr.isEmpty() || contactNumber.isEmpty() || address.isEmpty()) {
                JOptionPane.showMessageDialog(dialog,
                    "Please fill all required fields!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            try {
                int quantity = Integer.parseInt(quantityStr);

                if (quantity <= 0) {
                    JOptionPane.showMessageDialog(dialog,
                        "Quantity must be greater than 0!",
                        "Invalid Quantity",
                        JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Create table if not exists
                PreOrderDAO.createPreOrdersTable();

                // Add pre-order to database
                boolean success = PreOrderDAO.addPreOrder(
                    customerName,
                    productName,
                    quantity,
                    unit,
                    deliveryDate,
                    contactNumber,
                    address,
                    notes
                );

                if (success) {
                    JOptionPane.showMessageDialog(dialog,
                        "Pre-order submitted successfully!\n" +
                        "Product: " + productName + "\n" +
                        "Quantity: " + quantity + " " + unit + "\n" +
                        "Expected Delivery: " + deliveryDate + "\n\n" +
                        "You will be contacted soon!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    dialog.dispose();
                } else {
                    JOptionPane.showMessageDialog(dialog,
                        "Failed to submit pre-order!",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog,
                    "Please enter a valid quantity number!",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            }
        });

        cancelButton.addActionListener(e -> dialog.dispose());

        dialog.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerPotral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
