/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author Chenul Warnasooriya
 */
public class farmerPotral extends javax.swing.JFrame {

    private int currentFarmerId = 1; // Default farmer ID

    /**
     * Creates new form farmerPotral
     */
    public farmerPotral() {
        initComponents();
        setupTable();
        loadCropsFromDatabase();
        addButtonListeners();
    }

    /**
     * Constructor with farmer ID from login
     */
    public farmerPotral(int farmerId) {
        this.currentFarmerId = farmerId;
        initComponents();
        setupTable();
        loadCropsFromDatabase();
        addButtonListeners();

        // Set window properties
        setTitle("EcoFarm Connect - Farmer Portal");
        setSize(1200, 800);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * Add action listeners to buttons
     */
    private void addButtonListeners() {
        // Logout button (jButton1)
        jButton1.addActionListener(e -> {
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Are you sure you want to logout?",
                    "Confirm Logout",
                    JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                this.dispose();
                new login_signup().setVisible(true);
            }
        });

        // Update Crop Details button (jButton3)
        jButton3.addActionListener(e -> showUpdateCropDialog());

        // My Inventory menu item (jMenu1)
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInventoryWindow();
            }
        });

        // Add Notifications menu item programmatically
        JMenu notificationMenu = new JMenu("🔔 Notifications");
        notificationMenu.setFont(new Font("Arial", Font.PLAIN, 12));
        notificationMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openNotifications();
            }
        });
        jMenuBar1.add(notificationMenu);

        // Profile menu item (jMenu4)
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openProfile();
            }
        });
    }

    // Open notifications window
    private void openNotifications() {
        this.setVisible(false);
        new farmerNotification(currentFarmerId).setVisible(true);
    }

    // Open profile window
    private void openProfile() {
        this.setVisible(false);
        new farmerProfile(currentFarmerId).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log Out");

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setText("Add New ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 153, 255));
        jButton3.setText("Update Crop Details");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plant.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        jPanel2.setBackground(new java.awt.Color(51, 204, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        jMenu2.setText("My Crops");
        jMenuBar1.add(jMenu2);

        jMenu1.setText("My Inventory");
        jMenuBar1.add(jMenu1);

        jMenu4.setText("Profile");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(35, 35, 35)
                            .addComponent(jButton3)
                            .addGap(290, 290, 290)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        showAddCropDialog();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Helper method to setup table columns
    private void setupTable() {
        String[] columnNames = {"Crop Name", "Planting Date", "Growth Stage", "Expected Harvest", "Status"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable1.setModel(model);
        jTable1.setRowHeight(30);
        jTable1.setFont(new Font("Arial", Font.PLAIN, 13));
        jTable1.getTableHeader().setFont(new Font("Arial", Font.BOLD, 13));
        jTable1.getTableHeader().setBackground(new Color(34, 139, 34));
        jTable1.getTableHeader().setForeground(Color.WHITE);
    }

    // Load crops from database into table
    private void loadCropsFromDatabase() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing rows

        List<Object[]> crops = FarmerCropDAO.getAllCrops(currentFarmerId);

        for (Object[] crop : crops) {
            model.addRow(crop);
        }
    }

    // Show dialog to add new crop
    private void showAddCropDialog() {
        JDialog dialog = new JDialog(this, "Add New Crop", true);
        dialog.setLayout(new GridBagLayout());
        dialog.setSize(450, 400);
        dialog.setLocationRelativeTo(this);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 15, 10, 15);

        // Title
        JLabel titleLabel = new JLabel("🌾 Add New Crop");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
        titleLabel.setForeground(new Color(34, 139, 34));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        dialog.add(titleLabel, gbc);

        gbc.gridwidth = 1;

        // Crop Name
        gbc.gridy = 1;
        gbc.gridx = 0;
        JLabel nameLabel = new JLabel("Crop Name:");
        nameLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(nameLabel, gbc);

        gbc.gridx = 1;
        JTextField nameField = new JTextField(20);
        dialog.add(nameField, gbc);

        // Planting Date
        gbc.gridy = 2;
        gbc.gridx = 0;
        JLabel plantingLabel = new JLabel("Planting Date (YYYY-MM-DD):");
        plantingLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(plantingLabel, gbc);

        gbc.gridx = 1;
        JTextField plantingField = new JTextField("2024-11-25");
        dialog.add(plantingField, gbc);

        // Growth Stage
        gbc.gridy = 3;
        gbc.gridx = 0;
        JLabel stageLabel = new JLabel("Growth Stage:");
        stageLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(stageLabel, gbc);

        gbc.gridx = 1;
        String[] stages = {"Seedling", "Growing", "Flowering", "Mature", "Harvesting"};
        JComboBox<String> stageCombo = new JComboBox<>(stages);
        dialog.add(stageCombo, gbc);

        // Expected Harvest
        gbc.gridy = 4;
        gbc.gridx = 0;
        JLabel harvestLabel = new JLabel("Expected Harvest (YYYY-MM-DD):");
        harvestLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(harvestLabel, gbc);

        gbc.gridx = 1;
        JTextField harvestField = new JTextField("2025-01-25");
        dialog.add(harvestField, gbc);

        // Status
        gbc.gridy = 5;
        gbc.gridx = 0;
        JLabel statusLabel = new JLabel("Status:");
        statusLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(statusLabel, gbc);

        gbc.gridx = 1;
        String[] statuses = {"Healthy", "Needs Attention", "Diseased", "Ready"};
        JComboBox<String> statusCombo = new JComboBox<>(statuses);
        dialog.add(statusCombo, gbc);

        // Buttons
        gbc.gridy = 6;
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));

        JButton saveButton = new JButton("💾 Save Crop");
        saveButton.setBackground(new Color(40, 167, 69));
        saveButton.setForeground(Color.WHITE);
        saveButton.setFont(new Font("Arial", Font.BOLD, 13));
        saveButton.setFocusPainted(false);
        saveButton.setOpaque(true);
        saveButton.setBorderPainted(false);
        saveButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        saveButton.setPreferredSize(new Dimension(130, 35));

        JButton cancelButton = new JButton("❌ Cancel");
        cancelButton.setBackground(new Color(220, 53, 69));
        cancelButton.setForeground(Color.WHITE);
        cancelButton.setFont(new Font("Arial", Font.BOLD, 13));
        cancelButton.setFocusPainted(false);
        cancelButton.setOpaque(true);
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        cancelButton.setPreferredSize(new Dimension(130, 35));

        btnPanel.add(saveButton);
        btnPanel.add(cancelButton);
        dialog.add(btnPanel, gbc);

        // Save button action
        saveButton.addActionListener(e -> {
            String cropName = nameField.getText().trim();
            String plantingDate = plantingField.getText().trim();
            String growthStage = (String) stageCombo.getSelectedItem();
            String expectedHarvest = harvestField.getText().trim();
            String status = (String) statusCombo.getSelectedItem();

            if (cropName.isEmpty() || plantingDate.isEmpty() || expectedHarvest.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean success = FarmerCropDAO.addCrop(currentFarmerId, cropName, plantingDate, growthStage, expectedHarvest, status);

            if (success) {
                JOptionPane.showMessageDialog(dialog, "Crop added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadCropsFromDatabase();
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog, "Failed to add crop! Check database connection.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        cancelButton.addActionListener(e -> dialog.dispose());

        dialog.setVisible(true);
    }

    // Show dialog to update crop details
    private void showUpdateCropDialog() {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a crop to update!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String cropName = (String) model.getValueAt(selectedRow, 0);
        String currentPlantingDate = (String) model.getValueAt(selectedRow, 1);
        String currentGrowthStage = (String) model.getValueAt(selectedRow, 2);
        String currentExpectedHarvest = (String) model.getValueAt(selectedRow, 3);
        String currentStatus = (String) model.getValueAt(selectedRow, 4);

        JDialog dialog = new JDialog(this, "Update Crop Details", true);
        dialog.setLayout(new GridBagLayout());
        dialog.setSize(450, 450);
        dialog.setLocationRelativeTo(this);

        GridBagConstraints gbc = new GridBagConstraints();
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 15, 10, 15);

        // Title
        JLabel titleLabel = new JLabel("🔄 Update Crop Details");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
        titleLabel.setForeground(new Color(0, 123, 255));
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        dialog.add(titleLabel, gbc);

        gbc.gridwidth = 1;

        // Crop Name (Read-only display)
        gbc.gridy = 1;
        gbc.gridx = 0;
        JLabel cropLabel = new JLabel("Crop Name:");
        cropLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(cropLabel, gbc);

        gbc.gridx = 1;
        JLabel cropNameLabel = new JLabel(cropName);
        cropNameLabel.setFont(new Font("Arial", Font.PLAIN, 13));
        cropNameLabel.setForeground(new Color(34, 139, 34));
        dialog.add(cropNameLabel, gbc);

        // Planting Date
        gbc.gridy = 2;
        gbc.gridx = 0;
        JLabel plantingLabel = new JLabel("Planting Date:");
        plantingLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(plantingLabel, gbc);

        gbc.gridx = 1;
        JTextField plantingField = new JTextField(currentPlantingDate, 20);
        dialog.add(plantingField, gbc);

        // Growth Stage
        gbc.gridy = 3;
        gbc.gridx = 0;
        JLabel stageLabel = new JLabel("Growth Stage:");
        stageLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(stageLabel, gbc);

        gbc.gridx = 1;
        String[] stages = {"Seedling", "Growing", "Flowering", "Mature", "Harvesting", "Harvested"};
        JComboBox<String> stageCombo = new JComboBox<>(stages);
        stageCombo.setSelectedItem(currentGrowthStage);
        dialog.add(stageCombo, gbc);

        // Expected Harvest
        gbc.gridy = 4;
        gbc.gridx = 0;
        JLabel harvestLabel = new JLabel("Expected Harvest:");
        harvestLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(harvestLabel, gbc);

        gbc.gridx = 1;
        JTextField harvestField = new JTextField(currentExpectedHarvest, 20);
        dialog.add(harvestField, gbc);

        // Status
        gbc.gridy = 5;
        gbc.gridx = 0;
        JLabel statusLabel = new JLabel("Status:");
        statusLabel.setFont(new Font("Arial", Font.BOLD, 13));
        dialog.add(statusLabel, gbc);

        gbc.gridx = 1;
        String[] statuses = {"Healthy", "Needs Attention", "Diseased", "Ready", "Harvested"};
        JComboBox<String> statusCombo = new JComboBox<>(statuses);
        statusCombo.setSelectedItem(currentStatus);
        dialog.add(statusCombo, gbc);

        // Buttons
        gbc.gridy = 6;
        gbc.gridx = 0;
        gbc.gridwidth = 2;
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 15, 10));

        JButton updateButton = new JButton("✓ Update");
        updateButton.setBackground(new Color(0, 123, 255));
        updateButton.setForeground(Color.WHITE);
        updateButton.setFont(new Font("Arial", Font.BOLD, 13));
        updateButton.setFocusPainted(false);
        updateButton.setOpaque(true);
        updateButton.setBorderPainted(false);
        updateButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        updateButton.setPreferredSize(new Dimension(130, 35));

        JButton cancelButton = new JButton("❌ Cancel");
        cancelButton.setBackground(new Color(220, 53, 69));
        cancelButton.setForeground(Color.WHITE);
        cancelButton.setFont(new Font("Arial", Font.BOLD, 13));
        cancelButton.setFocusPainted(false);
        cancelButton.setOpaque(true);
        cancelButton.setBorderPainted(false);
        cancelButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        cancelButton.setPreferredSize(new Dimension(130, 35));

        btnPanel.add(updateButton);
        btnPanel.add(cancelButton);
        dialog.add(btnPanel, gbc);

        // Update button action
        updateButton.addActionListener(e -> {
            String newPlantingDate = plantingField.getText().trim();
            String newGrowthStage = (String) stageCombo.getSelectedItem();
            String newExpectedHarvest = harvestField.getText().trim();
            String newStatus = (String) statusCombo.getSelectedItem();

            if (newPlantingDate.isEmpty() || newExpectedHarvest.isEmpty()) {
                JOptionPane.showMessageDialog(dialog, "Please fill all fields!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            boolean success = FarmerCropDAO.updateCrop(currentFarmerId, cropName,
                    newPlantingDate, newGrowthStage, newExpectedHarvest, newStatus);

            if (success) {
                JOptionPane.showMessageDialog(dialog, "Crop updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                loadCropsFromDatabase();
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog, "Failed to update crop!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        });

        cancelButton.addActionListener(e -> dialog.dispose());

        dialog.setVisible(true);
    }

    // Show inventory window with tools and seeds tables
    private void showInventoryWindow() {
        JDialog inventoryDialog = new JDialog(this, "My Inventory - Tools & Seeds", false);
        inventoryDialog.setSize(900, 600);
        inventoryDialog.setLocationRelativeTo(this);
        inventoryDialog.setLayout(new BorderLayout(10, 10));

        // Main panel
        JPanel mainPanel = new JPanel(new BorderLayout(10, 10));
        mainPanel.setBorder(BorderFactory.createEmptyBorder(20, 20, 20, 20));
        mainPanel.setBackground(Color.WHITE);

        // Title
        JLabel titleLabel = new JLabel("📦 My Inventory Management");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 22));
        titleLabel.setForeground(new Color(34, 139, 34));
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);
        mainPanel.add(titleLabel, BorderLayout.NORTH);

        // Create tabbed pane for Tools and Seeds
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.setFont(new Font("Arial", Font.BOLD, 14));

        // Tools Panel
        JPanel toolsPanel = createToolsPanel();
        tabbedPane.addTab("🔧 Tools", toolsPanel);

        // Seeds Panel
        JPanel seedsPanel = createSeedsPanel();
        tabbedPane.addTab("🌱 Seeds", seedsPanel);

        mainPanel.add(tabbedPane, BorderLayout.CENTER);

        // Close button
        JButton closeButton = new JButton("✖ Close");
        closeButton.setBackground(new Color(220, 53, 69));
        closeButton.setForeground(Color.WHITE);
        closeButton.setFont(new Font("Arial", Font.BOLD, 14));
        closeButton.setFocusPainted(false);
        closeButton.setOpaque(true);
        closeButton.setBorderPainted(false);
        closeButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        closeButton.setPreferredSize(new Dimension(120, 40));
        closeButton.addActionListener(e -> inventoryDialog.dispose());

        JPanel bottomPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        bottomPanel.setBackground(Color.WHITE);
        bottomPanel.add(closeButton);
        mainPanel.add(bottomPanel, BorderLayout.SOUTH);

        inventoryDialog.add(mainPanel);
        inventoryDialog.setVisible(true);
    }

    // Create tools panel with table
    private JPanel createToolsPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panel.setBackground(Color.WHITE);

        // Title
        JLabel titleLabel = new JLabel("🔧 My Tools");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
        titleLabel.setForeground(new Color(0, 123, 255));

        // Create table
        String[] columnNames = {"Tool Name", "Condition", "Last Used", "Status"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        JTable toolsTable = new JTable(model);
        toolsTable.setRowHeight(30);
        toolsTable.setFont(new Font("Arial", Font.PLAIN, 13));
        toolsTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 13));
        toolsTable.getTableHeader().setBackground(new Color(0, 123, 255));
        toolsTable.getTableHeader().setForeground(Color.WHITE);
        toolsTable.setSelectionBackground(new Color(173, 216, 230));

        // Load tools from database
        List<Object[]> tools = InventoryDAO.getAllTools(currentFarmerId);
        for (Object[] tool : tools) {
            model.addRow(tool);
        }

        JScrollPane scrollPane = new JScrollPane(toolsTable);
        scrollPane.setBorder(BorderFactory.createLineBorder(new Color(0, 123, 255), 2));

        panel.add(titleLabel, BorderLayout.NORTH);
        panel.add(scrollPane, BorderLayout.CENTER);

        return panel;
    }

    // Create seeds panel with table
    private JPanel createSeedsPanel() {
        JPanel panel = new JPanel(new BorderLayout(10, 10));
        panel.setBorder(BorderFactory.createEmptyBorder(15, 15, 15, 15));
        panel.setBackground(Color.WHITE);

        // Title
        JLabel titleLabel = new JLabel("🌱 My Seeds Stock");
        titleLabel.setFont(new Font("Arial", Font.BOLD, 18));
        titleLabel.setForeground(new Color(40, 167, 69));

        // Create table
        String[] columnNames = {"Seed Name", "Quantity", "Unit", "Status"};
        DefaultTableModel model = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        JTable seedsTable = new JTable(model);
        seedsTable.setRowHeight(30);
        seedsTable.setFont(new Font("Arial", Font.PLAIN, 13));
        seedsTable.getTableHeader().setFont(new Font("Arial", Font.BOLD, 13));
        seedsTable.getTableHeader().setBackground(new Color(40, 167, 69));
        seedsTable.getTableHeader().setForeground(Color.WHITE);
        seedsTable.setSelectionBackground(new Color(144, 238, 144));

        // Load seeds from database
        List<Object[]> seeds = InventoryDAO.getAllSeeds(currentFarmerId);
        for (Object[] seed : seeds) {
            model.addRow(seed);
        }

        JScrollPane scrollPane = new JScrollPane(seedsTable);
        scrollPane.setBorder(BorderFactory.createLineBorder(new Color(40, 167, 69), 2));

        panel.add(titleLabel, BorderLayout.NORTH);
        panel.add(scrollPane, BorderLayout.CENTER);

        return panel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(farmerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(farmerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(farmerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(farmerPotral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new farmerPotral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
